import GameGrid from "@/components/GameGrid";
import GenreList from "@/components/GenreList";
import Navbar from "@/components/Navbar";
import PlatformSelector from "@/components/PlatformSelector";
import { Genre } from "@/hooks/useGenres";
import { Platform } from "@/hooks/usePlatforms";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [genre, setGenre] = useState<Genre | null>(null);
  const [platform, setPlatform] = useState<Platform | null>(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section>
          <Navbar></Navbar>
        </section>

        <div className="grid grid-cols-[200px,auto]">
          <aside className="">
            <GenreList selectedGenre={genre} setGenre={setGenre} />
          </aside>
          <main>
            <PlatformSelector setPlatform={setPlatform} />
            <GameGrid genre={genre} platform={platform} />
          </main>
        </div>
      </div>
    </>
  );
}
