import GameGrid from "@/components/GameGrid";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark:bg-black h-[100vh] ">
        <section>
          <Navbar></Navbar>
        </section>
        <main>
          <GameGrid />
        </main>
      </div>
    </>
  );
}
