import GameGrid from "@/components/GameGrid";
import GenreList from "@/components/GenreList";
import Navbar from "@/components/Navbar";
import PlatformSelector from "@/components/PlatformSelector";
import SortSelector from "@/components/SortSelector";
import { Genre } from "@/hooks/useGenres";
import { Platform } from "@/hooks/usePlatforms";
import Head from "next/head";
import { useState } from "react";

export interface GameQuery {
  genre: Genre | null;
  platform: Platform | null;
  sortOrder: string | null;
}
export default function Home() {
  const [gameQuery, setGameQuery] = useState<GameQuery>({} as GameQuery);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section>
          <Navbar></Navbar>
        </section>

        <div className="grid grid-cols-[200px,auto]">
          <aside className="">
            <GenreList
              selectedGenre={gameQuery.genre}
              setGenre={(genre) => {
                setGameQuery({ ...gameQuery, genre });
              }}
            />
          </aside>
          <main>
            <div className="flex">
              <PlatformSelector
                setPlatform={(platform) => {
                  setGameQuery({ ...gameQuery, platform });
                }}
              />
              <SortSelector
                setOrder={(sortOrder) =>
                  setGameQuery({ ...gameQuery, sortOrder })
                }
              />
            </div>

            <GameGrid gameQuery={gameQuery} />
          </main>
        </div>
      </div>
    </>
  );
}
